# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "pharo10", "actions" ]
  pull_request:
    branches: [ "pharo10" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-13
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: 'Pharo64-10'
      - uses: browser-actions/setup-chrome@v1
      - run: chromium --version
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g npm@latest
      - run: npm i ws
        working-directory: ./HTML/PharoJs-Examples/PjHelloWorldExpressApp
      - name: setup-xvfb
        uses: coactions/setup-xvfb@v1.0.1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Command to execute using xvfb
          run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
